site_name: INTERACT-PPI
nav:
  - Home: index.md
  - Project Overview: project_overview.md
  - Requirements: requirements.md
  - Modules:
      - PPI-interface residue extraction (Euclidean distance): modules/extract_interacting_residues.md
      - PPI-interface residue extraction (ESM-2): modules/esm2_extract_residue_embeddings.md
      - Interface Residue Extractor: modules/interface_residue_extractor.md
      - Extract Sequences: modules/sequence_extractor.md
