site_name: INTERACT-PPI Documentation

nav:
  - Home: index.md
  - Project Overview: project_overview.md
  - Requirements: requirements.md
  - Modules:
      - Extract Interacting Residues: modules/esm2_extract_residue_embeddings.md
      - Interface Residue Extractor: modules/interface_residue_extractor.md
      - Extract Sequences: modules/sequence_extractor.md
